version: "3.9"
services:
  web:
    build: .
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
